# Generated by Django 5.1.5 on 2025-02-01 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfricasTalkingSMS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('sent', 'Sent'), ('submitted', 'Submitted'), ('buffered', 'Buffered'), ('rejected', 'Rejected'), ('success', 'Success'), ('failed', 'Failed'), ('absent_subscriber', 'AbsentSubscriber'), ('expired', 'Expired')], max_length=50, null=True)),
                ('network_code', models.CharField(blank=True, choices=[('62120', 'Airtel Nigeria'), ('62130', 'MTN Nigeria'), ('62150', 'Glo Nigeria'), ('62160', 'Etisalat Nigeria'), ('63510', 'MTN Rwanda'), ('63513', 'Tigo Rwanda'), ('63514', 'Airtel Rwanda'), ('63902', 'Safaricom'), ('63903', 'Airtel Kenya'), ('63907', 'Orange Kenya'), ('63999', 'Equitel Kenya'), ('64002', 'Tigo Tanzania'), ('64003', 'Zantel Tanzania'), ('64004', 'Vodacom Tanzania'), ('64005', 'Airtel Tanzania'), ('64007', 'TTCL Tanzania'), ('64009', 'Halotel Tanzania'), ('64101', 'Airtel Uganda'), ('64110', 'MTN Uganda'), ('64111', 'UTL Uganda'), ('64114', 'Africell Uganda'), ('65001', 'TNM Malawi'), ('65010', 'Airtel Malawi'), ('99999', 'Athena')], max_length=50, null=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('InsufficientCredit', 'InsufficientCredit'), ('InvalidLinkId', 'InvalidLinkId'), ('UserIsInactive', 'UserIsInactive'), ('UserInBlackList', 'UserInBlackList'), ('UserAccountSuspended', 'UserAccountSuspended'), ('NotNetworkSubcriber', 'NotNetworkSubcriber'), ('UserNotSubscribedToProduct', 'UserNotSubscribedToProduct'), ('UserDoesNotExist', 'UserDoesNotExist'), ('DeliveryFailure', 'DeliveryFailure'), ('DoNotDisturbRejection', 'DoNotDisturbRejection')], max_length=50, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
        ),
    ]
