# Generated by Django 5.1.5 on 2025-02-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africas_talking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='africastalkingsms',
            old_name='reference_id',
            new_name='message_id',
        ),
        migrations.AddField(
            model_name='africastalkingsms',
            name='cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='africastalkingsms',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='africastalkingsms',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
