# Generated by Django 5.1.5 on 2025-02-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africas_talking', '0002_rename_reference_id_africastalkingsms_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='africastalkingsms',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='africastalkingsms',
            name='network_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='africastalkingsms',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
