name: sil

services:
  api:
    build:
      context: .
      target: builder
    ports:
      - "8000:8000"
    networks:
      - juno

  rabbit:
    image: rabbitmq
    expose:
      - 5672
    ports:
      - 5672:5672
    networks:
      - juno

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - juno

secrets:
  db-password:
    file: .db/password.txt

networks:
  juno:
