# Generated by Django 5.1.5 on 2025-02-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_order_products_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='+254704727291', max_length=15),
            preserve_default=False,
        ),
    ]
